learn_temp/learn_temp/urls.py
from django.contrib import admin
from django.urls import path, include
from tempApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path('tempApp/', include('tempApp.urls')),
]

learn_temp/tempApp/urls.py
from django.urls import path
from . import views

# Template Tagging

app_name = 'tempApp'

urlpatterns = [
    path("about/", views.about, name="about"),
    path("relative_url/", views.relative, name="relative"),
]

learn_temp/tempApp/models.py
from django.db import models

# Create your models here.

learn_temp/tempApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict= {'text': 'hello Vic', 'numbers':300}
    return render(request, 'tempApp/index.html', context_dict)

def about(request):
    return render(request, 'tempApp/about.html')

def relative(request):
    return render(request, 'tempApp/relative_url.html')

learn_temp/templates/tempApp/about.html
<!DOCTYPE html>
{% extends 'tempApp/base.html'%}

{% block body_block  %}
    <h1>This is my freaking about page..!</h1>
{% endblock  %}
</html>

learn_temp/templates/tempApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <div class="navigation">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Index</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'tempApp:relative' %}">RelativeURL<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tempApp:about' %}">About</a>
                </li>
                </ul>
            </div>
        </nav>
    </div>
    <!--End of Navigation -->
    <div class="container">
        {% block body_block %}
        <!--Put anything here for other pages. -->
            {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

learn_temp/templates/tempApp/index.html
<!DOCTYPE html>
{% extends 'tempApp/base.html'%}
{% load my_extras %}

{% block body_block %}
    <h1>WELCOME TO THE HOMEPAGE NIGGIE :) </h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero a in eum omnis veritatis ducimus laudantium nesciunt laborum. Velit nulla possimus explicabo iste dicta, obcaecati quidem exercitationem error maxime aliquam!</p>

    <h1>{{ text|cut:"hello" }}</h1>
    <h1>{{ numbers|add:"99" }}</h1>
{% endblock  %}

learn_temp/templates/tempApp/relative_url.html
<!DOCTYPE html>
{% extends 'tempApp/base.html'%}

{% block body_block %}
    <h1>This is the Relative URL page ok.</h1>
    {% endblock  %}
</html>